import clsx from 'clsx'
import Head from 'next/head'
import Link from 'next/link'
import { Button } from '../components/Button'
import { Header } from '../components/Header'
import { MoneyBackground } from '../components/MoneyBackground'

export default function Home() {
  return (
    <div>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet"
        />
        <title>Finance</title>
      </Head>

      <div className="flex flex-col h-screen w-screen bg-gray-50">
        <Header />
        <main className={clsx(`mt-20 flex flex-col items-center w-full h-full`)}>
          <div className={clsx(`w-full h-full max-w-6xl flex justify-between items-center`)}>
            <div>
              <MoneyBackground />
            </div>
            <div className="flex flex-col h-[497px] items-center">
              <h1 className="text-5xl text-center">
                Domine suas <br /> finanças e organize <br /> sua vida
              </h1>
              <Button asChild className="w-80 mt-16">
                <Link href="/signup">Crie sua conta</Link>
              </Button>
            </div>
          </div>
        </main>
      </div>
    </div>
  )
}
