import clsx from 'clsx'
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { parseCookies } from 'nookies'

import { Button } from '../components/Button'
import { HomeHeader } from '../components/HomeHeader'
import { MoneyBackground } from '../components/MoneyBackground'

export default function Home() {
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <title>Finance</title>
      </Head>

      <div className="flex flex-col h-screen w-screen bg-gray-50">
        <HomeHeader />
        <main className={clsx(`mt-20 flex flex-col items-center w-full h-full`)}>
          <div className={clsx(`w-full h-full max-w-6xl flex justify-between items-center`)}>
            <div>
              <MoneyBackground />
            </div>
            <div className="flex flex-col h-[497px] items-center">
              <h1 className="text-5xl text-center">
                Domine suas <br /> finanças e organize <br /> sua vida
              </h1>
              <Button asChild className="w-80 mt-16">
                <Link href="/signup">Crie sua conta</Link>
              </Button>
            </div>
          </div>
        </main>
      </div>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { 'finance.token': token } = parseCookies(context)

  if (token) {
    return {
      redirect: {
        destination: '/dashboard',
        permanent: false,
      },
    }
  }

  return {
    props: {},
  }
}
